name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: unit tests
      run: |
        sudo apt-get update && sudo apt-get install python3-dev python3-pip && sudo pip3 install -U -r test-requirements.txt && \
        mkdir ~/.cache && PYTHONPATH=. pytest -vv && PYTHONPATH=. pylint --fail-under=8.0 tests/*py pypcep/*py
